name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release

      - name: Generate deb package
        run: |
          cargo install cargo-deb
          cargo deb --output release

      - name: Generate AUR package
        run: |
          cargo install cargo-aur
          cargo aur pkgbuild
          mv target/cargo-aur/PKGBUILD release/
          mv target/cargo-aur/*.tar.gz release/
          mv target/release/sniplias release/sniplias-linux-x86_64

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.deb
            release/sniplias-*-x86_64.tar.gz
            release/sniplias-linux-x86_64
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: sniplias-bin
          pkgbuild: release/PKGBUILD
          commit_username: otomay
          commit_email: otomay@users.noreply.github.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519
